-- ✅ AGREGAR COLUMNA FALTANTE EN CATEGORIAS
PROMPT '🔧 Agregando columna FECHA_MODIFICACION a CATEGORIAS...'

ALTER TABLE CATEGORIAS 
ADD FECHA_MODIFICACION DATE;

PROMPT '✅ Columna FECHA_MODIFICACION agregada exitosamente!'

-- Verificar la estructura actualizada
PROMPT '📋 Verificando estructura de CATEGORIAS:'
DESC CATEGORIAS;

PROMPT '🎯 ¡Listo! Ahora puedes ejecutar la aplicación Spring Boot.'



-- ✅ VERIFICAR Y AGREGAR TODAS LAS COLUMNAS FALTANTES
PROMPT '🔍 Verificando columnas faltantes en todas las tablas...'

-- Verificar CATEGORIAS
SELECT 'CATEGORIAS' as TABLA, COLUMN_NAME 
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'CATEGORIAS'
ORDER BY COLUMN_ID;

-- Verificar PRODUCTOS  
SELECT 'PRODUCTOS' as TABLA, COLUMN_NAME 
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'PRODUCTOS'
ORDER BY COLUMN_ID;

-- Verificar USUARIOS
SELECT 'USUARIOS' as TABLA, COLUMN_NAME 
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'USUARIOS'
ORDER BY COLUMN_ID;

-- Verificar PROVEEDORES
SELECT 'PROVEEDORES' as TABLA, COLUMN_NAME 
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'PROVEEDORES'
ORDER BY COLUMN_ID;

PROMPT '📊 Verificación completada. Revisa si faltan más columnas.'



ALTER TABLE CATEGORIAS ADD FECHA_MODIFICACION DATE;







-- ✅ Verificación rápida antes de iniciar la aplicación
SELECT 'CATEGORIAS - OK' as TABLA, COUNT(*) as REGISTROS FROM CATEGORIAS
UNION ALL
SELECT 'PRODUCTOS - OK' as TABLA, COUNT(*) as REGISTROS FROM PRODUCTOS  
UNION ALL
SELECT 'USUARIOS - OK' as TABLA, COUNT(*) as REGISTROS FROM USUARIOS
UNION ALL
SELECT 'PROVEEDORES - OK' as TABLA, COUNT(*) as REGISTROS FROM PROVEEDORES;

-- 🔍 Verificar que todas las columnas existen
SELECT 'FECHA_MODIFICACION en CATEGORIAS' as VERIFICACION, 
       CASE WHEN COUNT(*) > 0 THEN '✅ EXISTE' ELSE '❌ FALTA' END as ESTADO
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'CATEGORIAS' AND COLUMN_NAME = 'FECHA_MODIFICACION';

PROMPT '🚀 ¡Base de datos lista! Ejecuta: gradlew bootRun'
