-- ✅ AGREGAR COLUMNA FALTANTE EN PRODUCTOS
PROMPT '🔧 Agregando columna FECHA_CREACION a PRODUCTOS...'

ALTER TABLE PRODUCTOS 
ADD FECHA_CREACION DATE DEFAULT SYSDATE;

PROMPT '✅ Columna FECHA_CREACION agregada exitosamente!'

-- Verificar la estructura actualizada
PROMPT '📋 Verificando estructura de PRODUCTOS:'
DESC PRODUCTOS;

PROMPT '🎯 ¡Listo! Ahora puedes ejecutar la aplicación Spring Boot.'







-- ✅ AGREGAR TODAS LAS COLUMNAS FALTANTES DE UNA VEZ
PROMPT '🔧 Agregando todas las columnas faltantes...'

-- Para PRODUCTOS
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PRODUCTOS ADD FECHA_CREACION DATE DEFAULT SYSDATE';
    DBMS_OUTPUT.PUT_LINE('✅ FECHA_CREACION agregada a PRODUCTOS');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️ FECHA_CREACION ya existe en PRODUCTOS');
        ELSE
            RAISE;
        END IF;
END;
/

-- Para PRODUCTOS - FECHA_MODIFICACION
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PRODUCTOS ADD FECHA_MODIFICACION DATE';
    DBMS_OUTPUT.PUT_LINE('✅ FECHA_MODIFICACION agregada a PRODUCTOS');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️ FECHA_MODIFICACION ya existe en PRODUCTOS');
        ELSE
            RAISE;
        END IF;
END;
/

-- Para USUARIOS - FECHA_CREACION
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE USUARIOS ADD FECHA_CREACION DATE DEFAULT SYSDATE';
    DBMS_OUTPUT.PUT_LINE('✅ FECHA_CREACION agregada a USUARIOS');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️ FECHA_CREACION ya existe en USUARIOS');
        ELSE
            RAISE;
        END IF;
END;
/

-- Para PROVEEDORES - FECHA_CREACION
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PROVEEDORES ADD FECHA_CREACION DATE DEFAULT SYSDATE';
    DBMS_OUTPUT.PUT_LINE('✅ FECHA_CREACION agregada a PROVEEDORES');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️ FECHA_CREACION ya existe en PROVEEDORES');
        ELSE
            RAISE;
        END IF;
END;
/

-- Para PROVEEDORES - FECHA_MODIFICACION
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PROVEEDORES ADD FECHA_MODIFICACION DATE';
    DBMS_OUTPUT.PUT_LINE('✅ FECHA_MODIFICACION agregada a PROVEEDORES');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️ FECHA_MODIFICACION ya existe en PROVEEDORES');
        ELSE
            RAISE;
        END IF;
END;
/

PROMPT '🎯 ¡Todas las columnas agregadas! Ahora ejecuta la aplicación.'
