-- ✅ AGREGAR TODAS LAS COLUMNAS FALTANTES EN PRODUCTOS
PROMPT '🔧 Agregando TODAS las columnas faltantes en PRODUCTOS...'

-- PRECIO_COMPRA
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PRODUCTOS ADD PRECIO_COMPRA NUMBER(10,2)';
    DBMS_OUTPUT.PUT_LINE('✅ PRECIO_COMPRA agregada');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️ PRECIO_COMPRA ya existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- FECHA_CREACION
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PRODUCTOS ADD FECHA_CREACION DATE DEFAULT SYSDATE';
    DBMS_OUTPUT.PUT_LINE('✅ FECHA_CREACION agregada');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️ FECHA_CREACION ya existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- FECHA_MODIFICACION
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PRODUCTOS ADD FECHA_MODIFICACION DATE';
    DBMS_OUTPUT.PUT_LINE('✅ FECHA_MODIFICACION agregada');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️ FECHA_MODIFICACION ya existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- REQUIERE_REFRIGERACION (como NUMBER para boolean)
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PRODUCTOS ADD REQUIERE_REFRIGERACION NUMBER(1) DEFAULT 0';
    DBMS_OUTPUT.PUT_LINE('✅ REQUIERE_REFRIGERACION agregada');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️ REQUIERE_REFRIGERACION ya existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- ES_PERECEDERO (como NUMBER para boolean)
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PRODUCTOS ADD ES_PERECEDERO NUMBER(1) DEFAULT 0';
    DBMS_OUTPUT.PUT_LINE('✅ ES_PERECEDERO agregada');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️ ES_PERECEDERO ya existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- EN_PROMOCION (como NUMBER para boolean)
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PRODUCTOS ADD EN_PROMOCION NUMBER(1) DEFAULT 0';
    DBMS_OUTPUT.PUT_LINE('✅ EN_PROMOCION agregada');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️ EN_PROMOCION ya existe');
        ELSE
            RAISE;
        END IF;
END;
/

PROMPT '📋 Verificando estructura final de PRODUCTOS:'
DESC PRODUCTOS;

PROMPT '🎯 ¡TODAS las columnas agregadas! Ahora ejecuta la aplicación.'











-- 🚀 SOLUCIÓN RÁPIDA - TODAS LAS COLUMNAS DE UNA VEZ
ALTER TABLE PRODUCTOS ADD (
    PRECIO_COMPRA NUMBER(10,2),
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_MODIFICACION DATE,
    REQUIERE_REFRIGERACION NUMBER(1) DEFAULT 0,
    ES_PERECEDERO NUMBER(1) DEFAULT 0,
    EN_PROMOCION NUMBER(1) DEFAULT 0
);

PROMPT '✅ ¡Todas las columnas agregadas de una vez!'
