-- ✅ AGREGAR COLUMNAS FALTANTES EN PROVEEDORES
PROMPT '🔧 Agregando columnas faltantes en PROVEEDORES...'

-- CONTACTO (que es la que falta según el error)
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PROVEEDORES ADD CONTACTO VARCHAR2(100)';
    DBMS_OUTPUT.PUT_LINE('✅ CONTACTO agregada');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️ CONTACTO ya existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- Verificar otras columnas que podrían faltar
-- APELLIDOS
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PROVEEDORES ADD APELLIDOS VARCHAR2(100)';
    DBMS_OUTPUT.PUT_LINE('✅ APELLIDOS agregada');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️ APELLIDOS ya existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- EMPRESA
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PROVEEDORES ADD EMPRESA VARCHAR2(150)';
    DBMS_OUTPUT.PUT_LINE('✅ EMPRESA agregada');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️ EMPRESA ya existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- TELEFONO_ALTERNATIVO
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PROVEEDORES ADD TELEFONO_ALTERNATIVO VARCHAR2(15)';
    DBMS_OUTPUT.PUT_LINE('✅ TELEFONO_ALTERNATIVO agregada');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️ TELEFONO_ALTERNATIVO ya existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- CONTACTO_PRINCIPAL
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PROVEEDORES ADD CONTACTO_PRINCIPAL VARCHAR2(100)';
    DBMS_OUTPUT.PUT_LINE('✅ CONTACTO_PRINCIPAL agregada');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️ CONTACTO_PRINCIPAL ya existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- DIAS_CREDITO
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PROVEEDORES ADD DIAS_CREDITO NUMBER(3) DEFAULT 0';
    DBMS_OUTPUT.PUT_LINE('✅ DIAS_CREDITO agregada');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️ DIAS_CREDITO ya existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- DESCUENTO_VOLUMEN
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PROVEEDORES ADD DESCUENTO_VOLUMEN NUMBER(5,2) DEFAULT 0';
    DBMS_OUTPUT.PUT_LINE('✅ DESCUENTO_VOLUMEN agregada');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️ DESCUENTO_VOLUMEN ya existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- BANCO
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PROVEEDORES ADD BANCO VARCHAR2(50)';
    DBMS_OUTPUT.PUT_LINE('✅ BANCO agregada');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️ BANCO ya existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- CUENTA_BANCARIA
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PROVEEDORES ADD CUENTA_BANCARIA VARCHAR2(20)';
    DBMS_OUTPUT.PUT_LINE('✅ CUENTA_BANCARIA agregada');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️ CUENTA_BANCARIA ya existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- ULTIMA_COMPRA
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PROVEEDORES ADD ULTIMA_COMPRA DATE';
    DBMS_OUTPUT.PUT_LINE('✅ ULTIMA_COMPRA agregada');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('⚠️ ULTIMA_COMPRA ya existe');
        ELSE
            RAISE;
        END IF;
END;
/

PROMPT '📋 Verificando estructura final de PROVEEDORES:'
DESC PROVEEDORES;

PROMPT '🎯 ¡Columnas agregadas! Ahora ejecuta Spring Boot.'



-- ✅ VERIFICAR QUE TODAS LAS TABLAS TENGAN LAS COLUMNAS CORRECTAS
PROMPT '🔍 Verificando estructura de todas las tablas para Spring Boot...'

PROMPT '📂 CATEGORIAS:'
DESC CATEGORIAS;

PROMPT '🏢 PROVEEDORES:'
DESC PROVEEDORES;

PROMPT '👤 USUARIOS:'
DESC USUARIOS;

PROMPT '📦 PRODUCTOS:'
DESC PRODUCTOS;

PROMPT '🛒 VENTAS:'
DESC VENTAS;

PROMPT '📋 DETALLE_VENTAS:'
DESC DETALLE_VENTAS;

PROMPT '✅ Verificación completada'
