-- =====================================================
-- SCRIPT 01: CREAR TODAS LAS SECUENCIAS
-- Secuencias para generar IDs automáticamente
-- =====================================================

-- Secuencias principales
CREATE SEQUENCE SEQ_CATEGORIAS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PROVEEDORES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PRODUCTOS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CLIENTES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_USUARIOS START WITH 1 INCREMENT BY 1 NOCACHE;

-- Secuencias de operaciones
CREATE SEQUENCE SEQ_VENTAS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DETALLE_VENTAS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MOVIMIENTOS_INVENTARIO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DEVOLUCIONES START WITH 1 INCREMENT BY 1 NOCACHE;

-- Secuencias de control
CREATE SEQUENCE SEQ_CAJA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CORTES_CAJA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_NOTIFICACIONES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ALERTAS_SISTEMA START WITH 1 INCREMENT BY 1 NOCACHE;

-- Secuencias de promociones
CREATE SEQUENCE SEQ_PROMOCIONES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_COMBOS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DETALLE_COMBOS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_OFERTAS_ESPECIALES START WITH 1 INCREMENT BY 1 NOCACHE;

-- Secuencias de sistema
CREATE SEQUENCE SEQ_REPORTES_GENERADOS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_AUDITORIA START WITH 1 INCREMENT BY 1 NOCACHE;

-- Secuencia para folios de venta (formato especial)
CREATE SEQUENCE SEQ_FOLIO_VENTA START WITH 1000 INCREMENT BY 1 NOCACHE;

COMMIT;

PROMPT ✅ Todas las secuencias creadas correctamente
