-- ========================================
-- DATOS ADICIONALES PARA SPRING BOOT
-- ========================================

PROMPT '🚀 === PREPARANDO DATOS PARA SPRING BOOT ==='
PROMPT ''

-- Agregar más productos para pruebas
INSERT INTO PRODUCTOS (ID_PRODUCTO, CODIGO_BARRAS, NOMBRE, DESCRIPCION, MARCA, PRESENTACION, COSTO_BASE, GASTOS_ADICIONALES, PRECIO_VENTA, STOCK_ACTUAL, STOCK_MINIMO, STOCK_MAXIMO, ID_CATEGORIA, ID_PROVEEDOR, ACTIVO, FECHA_REGISTRO) 
VALUES (4, '7501002234568', 'Yogurt Natural 1L', 'Yogurt natural', 'Danone', '1 Litro', 15.00, 2.00, 22.00, 40, 8, 150, 2, 2, 1, SYSDATE);

INSERT INTO PRODUCTOS (ID_PRODUCTO, CODIGO_BARRAS, NOMBRE, DESCRIPCION, MARCA, PRESENTACION, COSTO_BASE, GASTOS_ADICIONALES, PRECIO_VENTA, STOCK_ACTUAL, STOCK_MINIMO, STOCK_MAXIMO, ID_CATEGORIA, ID_PROVEEDOR, ACTIVO, FECHA_REGISTRO) 
VALUES (5, '7501003234567', 'Pan Blanco', 'Pan de caja blanco', 'Bimbo', '680g', 22.00, 3.00, 32.00, 30, 5, 100, 3, 3, 1, SYSDATE);

-- Verificar usuario admin para Spring Boot
PROMPT '👤 USUARIO ADMIN PARA SPRING BOOT:'
SELECT ID_USUARIO, USUARIO, NOMBRE, ROL, ACTIVO 
FROM USUARIOS 
WHERE USUARIO = 'admin';

COMMIT;

PROMPT ''
PROMPT '🎯 DATOS LISTOS PARA SPRING BOOT:'
PROMPT '   - Usuario: admin'
PROMPT '   - Password: admin (encriptado)'
PROMPT '   - 5 Categorías'
PROMPT '   - 4 Proveedores' 
PROMPT '   - 5 Productos'
PROMPT '   - Sistema de ventas funcional'
PROMPT ''
PROMPT '🚀 ¡LISTO PARA EJECUTAR: ./gradlew bootRun!'
