-- =====================================================
-- 📋 EJEMPLO DE ENTIDAD JAVA PARA PRODUCTOS
-- =====================================================

PROMPT '☕ === EJEMPLO DE ENTIDAD JAVA ==='
PROMPT ''
PROMPT 'Tu entidad Java debería verse así:'
PROMPT ''
PROMPT '@Entity'
PROMPT '@Table(name = "PRODUCTOS")'
PROMPT 'public class Producto {'
PROMPT ''
PROMPT '    @Id'
PROMPT '    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_productos")'
PROMPT '    @SequenceGenerator(name = "seq_productos", sequenceName = "SEQ_PRODUCTOS", allocationSize = 1)'
PROMPT '    @Column(name = "ID_PRODUCTO")'
PROMPT '    private Long idProducto;'
PROMPT ''
PROMPT '    @Column(name = "CODIGO_BARRAS")'
PROMPT '    private String codigoBarras;'
PROMPT ''
PROMPT '    @Column(name = "NOMBRE")'
PROMPT '    private String nombre;'
PROMPT ''
PROMPT '    @Column(name = "COSTO_BASE")'
PROMPT '    private BigDecimal costoBase;'
PROMPT ''
PROMPT '    @Column(name = "PRECIO_VENTA")'
PROMPT '    private BigDecimal precioVenta;'
PROMPT ''
PROMPT '    @Column(name = "STOCK_ACTUAL")'
PROMPT '    private Integer stockActual;'
PROMPT ''
PROMPT '    @Column(name = "VALOR_INVENTARIO")  // ← ¡ESTA COLUMNA YA FUNCIONA!'
PROMPT '    private BigDecimal valorInventario;'
PROMPT ''
PROMPT '    // ... getters y setters'
PROMPT '}'
PROMPT ''
PROMPT '✅ ¡Esta entidad funcionará perfectamente sin errores!'
