-- ========================================
-- VERIFICACIÓN FINAL DE LOS 18 TRIGGERS
-- ========================================

PROMPT '🏆 === VERIFICACIÓN FINAL DE LOS 18 TRIGGERS ==='
PROMPT ''

-- Lista completa de los 18 triggers esperados
PROMPT '📋 LISTA COMPLETA DE TRIGGERS:'

WITH triggers_esperados AS (
    SELECT 'TRG_PRODUCTOS_CALCULOS' as trigger_name, '1️⃣ CÁLCULOS' as grupo FROM dual UNION ALL
    SELECT 'TRG_STOCK_CONTROL', '1️⃣ CÁLCULOS' FROM dual UNION ALL
    SELECT 'TRG_ALERTAS_CADUCIDAD', '1️⃣ CÁLCULOS' FROM dual UNION ALL
    SELECT 'TRG_CONTROL_CAJA', '1️⃣ CÁLCULOS' FROM dual UNION ALL
    SELECT 'TRG_AUDITORIA_PRODUCTOS', '2️⃣ AUDITORÍA' FROM dual UNION ALL
    SELECT 'TRG_AUDITORIA_VENTAS', '2️⃣ AUDITORÍA' FROM dual UNION ALL
    SELECT 'TRG_AUDITORIA_USUARIOS', '2️⃣ AUDITORÍA' FROM dual UNION ALL
    SELECT 'TRG_NOTIFICACIONES_STOCK', '3️⃣ NOTIFICACIONES' FROM dual UNION ALL
    SELECT 'TRG_NOTIFICACIONES_CADUCIDAD', '3️⃣ NOTIFICACIONES' FROM dual UNION ALL
    SELECT 'TRG_NOTIFICACIONES_VENTAS', '3️⃣ NOTIFICACIONES' FROM dual UNION ALL
    SELECT 'TRG_NOTIFICACIONES_SISTEMA', '3️⃣ NOTIFICACIONES' FROM dual UNION ALL
    SELECT 'TRG_CALCULOS_VENTAS', '4️⃣ VENTAS' FROM dual UNION ALL
    SELECT 'TRG_CALCULOS_DETALLE_VENTAS', '4️⃣ VENTAS' FROM dual UNION ALL
    SELECT 'TRG_ACTUALIZAR_TOTALES_VENTA', '4️⃣ VENTAS' FROM dual UNION ALL
    SELECT 'TRG_CONTROL_DEVOLUCIONES', '4️⃣ VENTAS' FROM dual UNION ALL
    SELECT 'TRG_APLICACION_PROMOCIONES', '5️⃣ PROMOCIONES' FROM dual UNION ALL
    SELECT 'TRG_CONTROL_COMBOS', '5️⃣ PROMOCIONES' FROM dual UNION ALL
    SELECT 'TRG_GENERACION_REPORTES', '6️⃣ REPORTES' FROM dual UNION ALL
    SELECT 'TRG_CONTROL_SESIONES', '6️⃣ REPORTES' FROM dual
)
SELECT 
    te.grupo as "GRUPO",
    te.trigger_name as "TRIGGER",
    NVL(ut.status, '❌ NO EXISTE') as "ESTADO",
    CASE 
        WHEN ut.status = 'ENABLED' THEN '✅'
        WHEN ut.status IS NOT NULL THEN '⚠️'
        ELSE '❌'
    END as "OK"
FROM triggers_esperados te
LEFT JOIN user_triggers ut ON te.trigger_name = ut.trigger_name
ORDER BY te.grupo, te.trigger_name;

PROMPT ''
PROMPT '📊 RESUMEN POR GRUPOS:'

WITH triggers_esperados AS (
    SELECT 'TRG_PRODUCTOS_CALCULOS' as trigger_name, '1️⃣ CÁLCULOS' as grupo FROM dual UNION ALL
    SELECT 'TRG_STOCK_CONTROL', '1️⃣ CÁLCULOS' FROM dual UNION ALL
    SELECT 'TRG_ALERTAS_CADUCIDAD', '1️⃣ CÁLCULOS' FROM dual UNION ALL
    SELECT 'TRG_CONTROL_CAJA', '1️⃣ CÁLCULOS' FROM dual UNION ALL
    SELECT 'TRG_AUDITORIA_PRODUCTOS', '2️⃣ AUDITORÍA' FROM dual UNION ALL
    SELECT 'TRG_AUDITORIA_VENTAS', '2️⃣ AUDITORÍA' FROM dual UNION ALL
    SELECT 'TRG_AUDITORIA_USUARIOS', '2️⃣ AUDITORÍA' FROM dual UNION ALL
    SELECT 'TRG_NOTIFICACIONES_STOCK', '3️⃣ NOTIFICACIONES' FROM dual UNION ALL
    SELECT 'TRG_NOTIFICACIONES_CADUCIDAD', '3️⃣ NOTIFICACIONES' FROM dual UNION ALL
    SELECT 'TRG_NOTIFICACIONES_VENTAS', '3️⃣ NOTIFICACIONES' FROM dual UNION ALL
    SELECT 'TRG_NOTIFICACIONES_SISTEMA', '3️⃣ NOTIFICACIONES' FROM dual UNION ALL
    SELECT 'TRG_CALCULOS_VENTAS', '4️⃣ VENTAS' FROM dual UNION ALL
    SELECT 'TRG_CALCULOS_DETALLE_VENTAS', '4️⃣ VENTAS' FROM dual UNION ALL
    SELECT 'TRG_ACTUALIZAR_TOTALES_VENTA', '4️⃣ VENTAS' FROM dual UNION ALL
    SELECT 'TRG_CONTROL_DEVOLUCIONES', '4️⃣ VENTAS' FROM dual UNION ALL
    SELECT 'TRG_APLICACION_PROMOCIONES', '5️⃣ PROMOCIONES' FROM dual UNION ALL
    SELECT 'TRG_CONTROL_COMBOS', '5️⃣ PROMOCIONES' FROM dual UNION ALL
    SELECT 'TRG_GENERACION_REPORTES', '6️⃣ REPORTES' FROM dual UNION ALL
    SELECT 'TRG_CONTROL_SESIONES', '6️⃣ REPORTES' FROM dual
)
SELECT 
    te.grupo as "GRUPO",
    COUNT(*) as "ESPERADOS",
    COUNT(CASE WHEN ut.status = 'ENABLED' THEN 1 END) as "✅ FUNCIONANDO",
    COUNT(CASE WHEN ut.status IS NULL THEN 1 END) as "❌ FALTANTES",
    ROUND(COUNT(CASE WHEN ut.status = 'ENABLED' THEN 1 END) * 100.0 / COUNT(*), 1) as "% ÉXITO"
FROM triggers_esperados te
LEFT JOIN user_triggers ut ON te.trigger_name = ut.trigger_name
GROUP BY te.grupo
ORDER BY te.grupo;

PROMPT ''
PROMPT '🎯 ESTADÍSTICAS FINALES:'

WITH triggers_esperados AS (
    SELECT 'TRG_PRODUCTOS_CALCULOS' as trigger_name FROM dual UNION ALL
    SELECT 'TRG_STOCK_CONTROL' FROM dual UNION ALL
    SELECT 'TRG_ALERTAS_CADUCIDAD' FROM dual UNION ALL
    SELECT 'TRG_CONTROL_CAJA' FROM dual UNION ALL
    SELECT 'TRG_AUDITORIA_PRODUCTOS' FROM dual UNION ALL
    SELECT 'TRG_AUDITORIA_VENTAS' FROM dual UNION ALL
    SELECT 'TRG_AUDITORIA_USUARIOS' FROM dual UNION ALL
    SELECT 'TRG_NOTIFICACIONES_STOCK' FROM dual UNION ALL
    SELECT 'TRG_NOTIFICACIONES_CADUCIDAD' FROM dual UNION ALL
    SELECT 'TRG_NOTIFICACIONES_VENTAS' FROM dual UNION ALL
    SELECT 'TRG_NOTIFICACIONES_SISTEMA' FROM dual UNION ALL
    SELECT 'TRG_CALCULOS_VENTAS' FROM dual UNION ALL
    SELECT 'TRG_CALCULOS_DETALLE_VENTAS' FROM dual UNION ALL
    SELECT 'TRG_ACTUALIZAR_TOTALES_VENTA' FROM dual UNION ALL
    SELECT 'TRG_CONTROL_DEVOLUCIONES' FROM dual UNION ALL
    SELECT 'TRG_APLICACION_PROMOCIONES' FROM dual UNION ALL
    SELECT 'TRG_CONTROL_COMBOS' FROM dual UNION ALL
    SELECT 'TRG_GENERACION_REPORTES' FROM dual UNION ALL
    SELECT 'TRG_CONTROL_SESIONES' FROM dual
)
SELECT 
    18 as "🎯 TRIGGERS_ESPERADOS",
    COUNT(CASE WHEN ut.status = 'ENABLED' THEN 1 END) as "✅ FUNCIONANDO",
    COUNT(CASE WHEN ut.status IS NULL THEN 1 END) as "❌ FALTANTES",
    COUNT(CASE WHEN ut.status != 'ENABLED' AND ut.status IS NOT NULL THEN 1 END) as "⚠️ CON_ERRORES",
    ROUND(COUNT(CASE WHEN ut.status = 'ENABLED' THEN 1 END) * 100.0 / 18, 1) as "📊 % COMPLETADO"
FROM triggers_esperados te
LEFT JOIN user_triggers ut ON te.trigger_name = ut.trigger_name;

PROMPT ''
PROMPT '🏆🏆🏆 === SISTEMA LA MODERNA ==='
PROMPT '🎉 ¡VERIFICACIÓN COMPLETA FINALIZADA!'
PROMPT ''
