-- ========================================
-- VERIFICACIÓN COMPLETA DE TODOS LOS TRIGGERS
-- ========================================

PROMPT '🔍 === VERIFICACIÓN COMPLETA DEL SISTEMA DE TRIGGERS ==='
PROMPT ''

-- Contar todos los triggers por grupo
PROMPT '📊 RESUMEN POR GRUPOS:'

SELECT 
    CASE 
        WHEN trigger_name IN ('TRG_PRODUCTOS_CALCULOS', 'TRG_STOCK_CONTROL', 'TRG_ALERTAS_CADUCIDAD', 'TRG_CONTROL_CAJA') 
        THEN 'GRUPO 1 - CÁLCULOS'
        WHEN trigger_name IN ('TRG_AUDITORIA_PRODUCTOS', 'TRG_AUDITORIA_VENTAS', 'TRG_AUDITORIA_USUARIOS') 
        THEN 'GRUPO 2 - AUDITORÍA'
        WHEN trigger_name IN ('TRG_NOTIFICACIONES_STOCK', 'TRG_NOTIFICACIONES_CADUCIDAD', 'TRG_NOTIFICACIONES_VENTAS', 'TRG_NOTIFICACIONES_SISTEMA') 
        THEN 'GRUPO 3 - NOTIFICACIONES'
        WHEN trigger_name IN ('TRG_CALCULOS_VENTAS', 'TRG_CALCULOS_DETALLE_VENTAS', 'TRG_ACTUALIZAR_TOTALES_VENTA', 'TRG_CONTROL_DEVOLUCIONES') 
        THEN 'GRUPO 4 - VENTAS'
        WHEN trigger_name IN ('TRG_APLICACION_PROMOCIONES', 'TRG_CONTROL_COMBOS') 
        THEN 'GRUPO 5 - PROMOCIONES'
        WHEN trigger_name IN ('TRG_GENERACION_REPORTES', 'TRG_CONTROL_SESIONES') 
        THEN 'GRUPO 6 - REPORTES'
        ELSE 'OTROS'
    END as "GRUPO",
    COUNT(*) as "TRIGGERS",
    COUNT(CASE WHEN status = 'ENABLED' THEN 1 END) as "FUNCIONANDO"
FROM user_triggers 
WHERE trigger_name LIKE 'TRG_%'
GROUP BY 
    CASE 
        WHEN trigger_name IN ('TRG_PRODUCTOS_CALCULOS', 'TRG_STOCK_CONTROL', 'TRG_ALERTAS_CADUCIDAD', 'TRG_CONTROL_CAJA') 
        THEN 'GRUPO 1 - CÁLCULOS'
        WHEN trigger_name IN ('TRG_AUDITORIA_PRODUCTOS', 'TRG_AUDITORIA_VENTAS', 'TRG_AUDITORIA_USUARIOS') 
        THEN 'GRUPO 2 - AUDITORÍA'
        WHEN trigger_name IN ('TRG_NOTIFICACIONES_STOCK', 'TRG_NOTIFICACIONES_CADUCIDAD', 'TRG_NOTIFICACIONES_VENTAS', 'TRG_NOTIFICACIONES_SISTEMA') 
        THEN 'GRUPO 3 - NOTIFICACIONES'
        WHEN trigger_name IN ('TRG_CALCULOS_VENTAS', 'TRG_CALCULOS_DETALLE_VENTAS', 'TRG_ACTUALIZAR_TOTALES_VENTA', 'TRG_CONTROL_DEVOLUCIONES') 
        THEN 'GRUPO 4 - VENTAS'
        WHEN trigger_name IN ('TRG_APLICACION_PROMOCIONES', 'TRG_CONTROL_COMBOS') 
        THEN 'GRUPO 5 - PROMOCIONES'
        WHEN trigger_name IN ('TRG_GENERACION_REPORTES', 'TRG_CONTROL_SESIONES') 
        THEN 'GRUPO 6 - REPORTES'
        ELSE 'OTROS'
    END
ORDER BY 1;

PROMPT ''
PROMPT '🎯 TODOS LOS TRIGGERS DEL SISTEMA:'

SELECT 
    trigger_name as "TRIGGER",
    status as "ESTADO",
    table_name as "TABLA"
FROM user_triggers 
WHERE trigger_name LIKE 'TRG_%'
ORDER BY trigger_name;

PROMPT ''
PROMPT '📈 ESTADÍSTICAS FINALES:'

SELECT 
    COUNT(*) as "TOTAL_TRIGGERS",
    COUNT(CASE WHEN status = 'ENABLED' THEN 1 END) as "FUNCIONANDO",
    COUNT(CASE WHEN status != 'ENABLED' THEN 1 END) as "CON_ERRORES"
FROM user_triggers 
WHERE trigger_name LIKE 'TRG_%';

PROMPT ''
PROMPT '🏆 === SISTEMA DE TRIGGERS COMPLETADO ==='
PROMPT '🎉 ¡18 TRIGGERS INTELIGENTES FUNCIONANDO!'
PROMPT ''
